### ISSUE TITLE
FFI CudaTensor

### ISSUE THREAD

**Issue by xmb-cipher** [Atcold/Torch-Developer-Guide#10]
I tried the following but failed. Could you please have a look at your convenience? 
Thanks very much.

The files are

fofe.cu
```cpp
#include <THC/THC.h>
void LowerTriangular(
    THCState *state, 
    THCudaTensor *alpha, 
    THCudaIntTensor *position, 
    THCudaTensor *memory) {
}
```

Makefile
```bash
TORCH_DIR =$(HOME)/torch/install

LIBOPTS = \
	-I$(TORCH_DIR)/include/TH \
	-I$(TORCH_DIR)/include \
	-L$(TORCH_DIR)/lib \
	-lTHC

NVCC_FLAGS = -shared -arch sm_35 --compiler-options '-fPIC' 
NVCC = nvcc

libfofe.so : fofe.cu
	$(NVCC) $< $(LIBOPTS) $(NVCC_FLAGS) -o $@

clean :
	rm *.so
```

and main.lua
```lua
require 'cutorch'

local ffi = require 'ffi'
ffi.cdef[[
    void LowerTriangular(
        THCState *state, 
        THCudaTensor *alpha, 
        THCudaIntTensor *position, 
        THCudaTensor *memory)
]]

local C = ffi.load(paths.cwd() .. '/libfofe.so')
local THCState_ptr = ffi.typeof('THCState*')


local nExample = 16
local alpha = torch.range(1, nExample):cuda()
local position = torch.range(1, nExample):cudaInt()
local memory = torch.Tensor(nExample, nExample):zero():cuda()

C.Lowertriangular(
    THCState_ptr(cutorch.getState()),
    alpha:cdata(),
    position:cdata(),
    memory:cdata()
)

print(memory)
```

which gives 
```
undefined symbol: LowerTriangular
```

**Comment by galv** [comment]
A hunch, but I'm very certain it's correct:

Wrap all of fofe.cu in a `extern "C" { <your code here> }` block.

Probably the host C++ compiler is being called by default instead of the C
compiler, and this is name mangling LowerTriangular to be another symbol
name.

Do `nm libfofe.so | grep LowerTriangular` to see if your symbol name was
mangled.

**Comment by xmb-cipher** [comment]
Thanks for your response. It is due to name mangling.

**Comment by Atcold** [comment]
@xmb-cipher, yes, @galv is correct.
I was planning to add a section for CUDA and C++ (both of them have this issue), given that this error stuck me as well, some time ago.
