### ISSUE TITLE
How to show the codes when debugging?

### ISSUE THREAD

**Issue by panfengli** [Atcold/Torch-Developer-Guide#11]
Is there a similar function like l(ist) in python gdb, so we can see the codes when debugging?

**Comment by Atcold** [comment]
Not that I am aware. I simply keep *Vim* open on a split screen. It's a bit painful, but it does the job.

**Comment by SilvesterHsu** [comment]
@panfengli, try [Zerobrane](https://studio.zerobrane.com/). But in some situation, you still need @Atcold's debug.
