### ISSUE TITLE
Breakpoint doesn't work on my computer

### ISSUE THREAD

**Issue by SilvesterHsu** [Atcold/Torch-Developer-Guide#9]
It didn't get expect result. Maybe I did something wrong.
I open two terminal, and type `th -e "require('mobdebug').listen()"` in the first terminal. 
It shows `Lua Remote Debugger
Run the program you wish to debug` 
So I type `th test.lua` in the another terminal, and the first terminal shows
```
Lua Remote Debugger
Run the program you wish to debug
Paused at file /users/sean/torch/install/share/lua/5.1/trepl/init.lua`
`Type 'help' for commands`
`>`
```
To test the breakpoint, I type `setb - 5` in order to set a breakpoint in line 5. After that I type `run`, only to find that the program is finished, so I am wondering whether I did something wrong.

The code are as followed,
```
# sean @ Live-409-S in ~/Desktop/tutorials/ex on git:master x [12:55:36] C:130
$ th -e "require('mobdebug').listen()"
Lua Remote Debugger
Run the program you wish to debug
Paused at file /users/sean/torch/install/share/lua/5.1/trepl/init.lua
Type 'help' for commands
`>` setb - 5
`>` run
Program finished
```

**Comment by Atcold** [comment]
Hi @SSeanHsu. Can you also provide your code?
It's likely that line `5` does not contain any instruction, and therefore the debugger cannot stop at any location.

**Comment by SilvesterHsu** [comment]
I am so happy to receive your reply. :D  And here is my test code:

```lua
 1 require ('mobdebug').start()
 2 require 'image'
 3 print("Project Start...")
 4
 5 array={}
 6 for i=1,3 do
 7    array[i]={}
 8    for j=1,3 do
 9       array[i][j]=i*j
10    end
11 end
12 print("Project Finish")
```

After setting a breakpoint in line `5`, and running the program, "Project Finish" shouldn't be printed. Am I right?

**Comment by Atcold** [comment]
~~@SSeanHsu, you can use a *breakpoint* to stop execution on a function call.
At line `5` you have only a statement. Therefore,~~ you may want to use `setw` to set a *watch* on the `array` variable.
Let me know if it works.

**Comment by SilvesterHsu** [comment]
Awesome! It works. Whats more, I find that it's my bad to use `setb - 5` rather than `setb test.lua 5`. Now everything work fine on my computer. Thanks a lot :D

**Comment by Atcold** [comment]
LOL... In fact, the debugger told you:
```
Paused at file /users/sean/torch/install/share/lua/5.1/trepl/init.lua
```
So, at line `5` of `/users/sean/torch/install/share/lua/5.1/trepl/init.lua` there is nothing.
```
  1 --[============================================================================[
  2    REPL: A REPL for Lua (with support for Torch objects).                       
  3                                                                                 
  4    This REPL is embeddable, and doesn't depend on C libraries.                  
  5    If readline.so is built and found at runtime, then tab-completion is enabled.
  6                                                                                 
  7    Support for SHELL commands:                                                  
  8    > $ ls                                                                       
  9    > $ ll                                                                       
 10    > $ ls -l                                                                    
 11    (prepend any command by $, from the Lua interpreter)                         
 12                                                                                 
 13    Copyright: MIT / BSD / Do whatever you want with it.                         
 14    Clement Farabet, 2013                                                        
 15 --]============================================================================]
```
Specifying the file name solved the trick.
